name: Experiment
on: 
  schedule:
  - cron: "*/5 * * * *"

env:
  TEST: ${{ secrets.TEST }}

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: Run python script
      shell: python
      run: |
        print(${{ env.TEST }})
